### PR TITLE
Add Python script

### PR DESCRIPTION
**Pull request by haseebT**

### CODE REVIEW

**Comment by kmahyyg** [comment]
Could you please also modify the readme file to offer an instruction to users?

**Comment by haseebT** [comment]
Do you want me to just edit the section under PR Welcome or create a new Python header?

**Comment by kmahyyg** [comment]
> Do you want me to just edit the section under PR Welcome or create a new Python header?

Do whatever you want.

**Comment by haseebT** [comment]
Done

**Pull request merged**
