### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by pdelteil**

### CODE REVIEW

**Comment by kmahyyg** [comment]
Your pull request is welcomed. However, on my point of view, the seeking ability is essential to the hackers, and also, it's so famous on the page "1 release".

So, so sorry, this PR will never be merged.

**Comment by kmahyyg** [comment]
By the way, I strongly suggest everyone ignore the release and review the code first. That will help them understand how this works.

**Comment by pdelteil** [comment]
Hello,

It's ok you like things complicated.

Java is old. I did check the source code first, but since you didn't
include the external libs, it won't compile.

Even the most 'hacker-like' tools have step by step instructions to
deploy/install/run. It's a waist of time, and it's nothing you could learn
out of it.




Saludos,


*Philippe Delteil*Cel: +56 9 4456.12.06
Santiago de Chile

**Comment by kmahyyg** [comment]
Well I updated the readme. Added dependencies.

I was trying to do that in a much more easier way via passlib&openssl in Python 3.

However, I failed. Seems that `org.bouncycastle` has something different in PBKDF2-SHA1-HMAC.

due to the mremoteng use the `bouncycastle` , this lib only has Java and csharp version.

That's why it was made in JAVA.

**Pull request closed without merging**
